export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className=''>
        {children}
      </body>
    </html>
  )
}
